.PHONY: clean All

All:
	@echo "----------Building project:[ constantsRoomProgram - Debug ]----------"
	@cd "constantsRoomProgram" && "$(MAKE)" -f  "constantsRoomProgram.mk"
clean:
	@echo "----------Cleaning project:[ constantsRoomProgram - Debug ]----------"
	@cd "constantsRoomProgram" && "$(MAKE)" -f  "constantsRoomProgram.mk" clean
