.PHONY: clean All

All:
	@echo "----------Building project:[ section11challenge - Debug ]----------"
	@cd "section11challenge" && "$(MAKE)" -f  "section11challenge.mk"
clean:
	@echo "----------Cleaning project:[ section11challenge - Debug ]----------"
	@cd "section11challenge" && "$(MAKE)" -f  "section11challenge.mk" clean
