.PHONY: clean All

All:
	@echo "----------Building project:[ PracticeIO - Debug ]----------"
	@cd "PracticeIO" && "$(MAKE)" -f  "PracticeIO.mk"
clean:
	@echo "----------Cleaning project:[ PracticeIO - Debug ]----------"
	@cd "PracticeIO" && "$(MAKE)" -f  "PracticeIO.mk" clean
