.PHONY: clean All

All:
	@echo "----------Building project:[ section13challenge - Debug ]----------"
	@cd "section13challenge" && "$(MAKE)" -f  "section13challenge.mk"
clean:
	@echo "----------Cleaning project:[ section13challenge - Debug ]----------"
	@cd "section13challenge" && "$(MAKE)" -f  "section13challenge.mk" clean
