.PHONY: clean All

All:
	@echo "----------Building project:[ section9menuChallenge - Debug ]----------"
	@cd "section9menuChallenge" && "$(MAKE)" -f  "section9menuChallenge.mk"
clean:
	@echo "----------Cleaning project:[ section9menuChallenge - Debug ]----------"
	@cd "section9menuChallenge" && "$(MAKE)" -f  "section9menuChallenge.mk" clean
