.PHONY: clean All

All:
	@echo "----------Building project:[ FirstProgram - Debug ]----------"
	@cd "FirstProject" && "$(MAKE)" -f  "FirstProgram.mk"
clean:
	@echo "----------Cleaning project:[ FirstProgram - Debug ]----------"
	@cd "FirstProject" && "$(MAKE)" -f  "FirstProgram.mk" clean
