.PHONY: clean All

All:
	@echo "----------Building project:[ findNumberInVector - Debug ]----------"
	@cd "findNumberInVector" && "$(MAKE)" -f  "findNumberInVector.mk"
clean:
	@echo "----------Cleaning project:[ findNumberInVector - Debug ]----------"
	@cd "findNumberInVector" && "$(MAKE)" -f  "findNumberInVector.mk" clean
