.PHONY: clean All

All:
	@echo "----------Building project:[ section10assignment - Debug ]----------"
	@cd "section10assignment" && "$(MAKE)" -f  "section10assignment.mk"
clean:
	@echo "----------Cleaning project:[ section10assignment - Debug ]----------"
	@cd "section10assignment" && "$(MAKE)" -f  "section10assignment.mk" clean
