.PHONY: clean All

All:
	@echo "----------Building project:[ section12challenge - Debug ]----------"
	@cd "section12challenge" && "$(MAKE)" -f  "section12challenge.mk"
clean:
	@echo "----------Cleaning project:[ section12challenge - Debug ]----------"
	@cd "section12challenge" && "$(MAKE)" -f  "section12challenge.mk" clean
