.PHONY: clean All

All:
	@echo "----------Building project:[ sec7challengeAgain - Debug ]----------"
	@cd "sec7challengeAgain" && "$(MAKE)" -f  "sec7challengeAgain.mk"
clean:
	@echo "----------Cleaning project:[ sec7challengeAgain - Debug ]----------"
	@cd "sec7challengeAgain" && "$(MAKE)" -f  "sec7challengeAgain.mk" clean
